#---------------------#
#Sping Boot会自动加载配置文件并且根据配置文件的信息建立数据库的连接池
#推荐采用yaml作为配置文件的格式
#---------------------#
spring:
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/SpringBootWithRedis
    username: root
    password: 123456
    driver-class-name: org.gjt.mm.mysql.Driver

  #配置Redis
  redis:
    # redis数据库索引（默认为0），我们使用索引为1的数据库
    database: 1
    # redis服务器地址（默认为localhost）
    host: localhost
    # redis端口（默认为6379）
    port: 6379
    # redis访问密码（默认为空）
    password:
    # redis连接超时时间（单位为毫秒）
    timeout: 0
    # redis连接池配置
    pool:
      # 最大可用连接数（默认为8，负数表示无限）
      max-active: 8
      # 最大空闲连接数（默认为8，负数表示无限）
      max-idle: 8
      # 最小空闲连接数（默认为0，该值只有为正数才有作用）
      min-idle: 0
      # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
      max-wait: -1

# 服务器配置
server:
  port: 8080

# mybatis配置
mybatis:
  # 配置映射类所在包名
  type-aliases-package: com.ncu.jerry.dao
  # 配置mapper xml文件所在路径，这里是一个数组
  mapper-locations:
    - mappers/ProductMapper.xml


logging:
  level:
    com.ncu.jerry: DEBUG

---
spring:
  profiles: test
  # 数据库配置
  datasource:
    url: jdbc:h2:mem:test
    username: root
    password: 123456
    driver-class-name: org.h2.Driver
    # schema.sql用于存放我们的建表语句，data.sql用于存放insert的数据
    # 初始化所需要的表结构以及数据，并在测试结束时销毁
    schema: classpath:schema.sql
    data: classpath:data.sql
